tap "anchore/grype"
tap "blacknon/hwatch"
tap "buildpacks/tap"
tap "fluxcd/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "int128/kubelogin"
tap "jplsek/tap"
tap "oven-sh/bun"
tap "spring-io/tap"
tap "tilt-dev/tap"
tap "tnk-studio/tools"
tap "trufflesecurity/trufflehog"
tap "vmware-tanzu/tanzu"
tap "vmware/pinniped", "https://github.com/vmware/homebrew-pinniped.git"
tap "yolossn/tap"
# WHATWG-compliant and fast URL parser written in modern C++
brew "ada-url"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Core c99 package for AWS SDK for C
brew "aws-c-common"
# C99 library implementing AWS SDK specific utilities
brew "aws-c-sdkutils"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# C library implementing the SSH2 protocol
brew "libssh2"
# Port of http_parser to llparse
brew "llhttp"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Linux/OSX/FreeBSD resource monitor
brew "bpytop"
# XML-based font configuration API for X Windows
brew "fontconfig"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Core application library for C
brew "glib"
# Easily download, build, install, upgrade, and uninstall Python packages
brew "python-setuptools"
# Calico CLI tool
brew "calicoctl"
# Next-generation test runner for Rust
brew "cargo-nextest"
# C Foreign Function Interface for Python
brew "cffi"
# Create and view interactive cheat sheets for *nix commands
brew "cheat"
# Cross-platform make
brew "cmake"
# GNU multiple precision arithmetic library
brew "gmp"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Cryptographic recipes and primitives for Python
brew "cryptography"
# TIFF library and utilities
brew "libtiff"
# Image format providing lossless and lossy compression for web images
brew "webp"
# Development kit for the Java programming language
brew "openjdk"
# OWASP dependency-check
brew "dependency-check"
# Load/unload environment variables based on $PWD
brew "direnv"
# Command-line tool to interact with exercism.io
brew "exercism"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# MP3 player for Linux and UNIX
brew "mpg123"
# VP8/VP9 video codec
brew "libvpx"
# Low-level access to audio, keyboard, mouse, joystick, and graphics
brew "sdl3"
# H.265/HEVC encoder
brew "x265"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# HTTP/2 C Library
brew "libnghttp2"
# Unicode conversion routines, fast
brew "simdutf"
# C++ lexer for extracting named exports from CommonJS modules
brew "merve"
# SIMD-accelerated C++ JSON parser
brew "simdjson"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Firebase command-line tools
brew "firebase-cli"
# Fast and simple Node.js version manager
brew "fnm"
# Minimalistic plugin API for video effects
brew "frei0r"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Command-line fuzzy finder written in Go
brew "fzf"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# GitHub command-line tool
brew "gh"
# Library for JPEG-2000 image manipulation
brew "openjpeg"
# Image processing and image analysis library
brew "leptonica"
# Framework for layout and rendering of i18n text
brew "pango"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Tcl/Tk UI for the git revision control system
brew "git-gui"
# Git extension for versioning large files
brew "git-lfs"
# CLI tool for including co-authors in commits
brew "git-mob"
# Run gitlab pipelines locally as shell executor or docker executor
brew "gitlab-ci-local"
# Open-source GitLab command-line tool
brew "glab"
# Render markdown on the CLI
brew "glow"
# Library to load and enumerate PKCS#11 modules
brew "p11-kit"
# X.509 and CMS library
brew "libksba"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Library access to GnuPG
brew "gpgme"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# Kubernetes package manager
brew "helm"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# Modern alternative to the watch command
brew "hwatch"
# Manage your Java environment
brew "jenv"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Handy way to save and run project-specific commands
brew "just"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Blu-Ray disc playback library for media players like VLC
brew "libbluray"
# Light HTTP/1.1 server library
brew "libmicrohttpd"
# Postgres C API library
brew "libpq"
# Reliable Internet Stream Transport (RIST)
brew "librist"
# Library to render SVG files using Cairo
brew "librsvg"
# C library SSHv1/SSHv2 client and server protocols
brew "libssh"
# Transcode video stabilization plugin
brew "libvidstab"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Powerful, lightweight programming language
brew "lua"
# Just-In-Time Compiler (JIT) for the Lua programming language
brew "luajit"
# Java-based project management
brew "maven"
# Run a Kubernetes cluster locally
brew "minikube"
# Nice to use pager for humans
brew "moor"
# Library for a binary-based efficient data interchange format
brew "msgpack"
# NCurses Disk Usage
brew "ncdu"
# Scalable overlay networking tool for connecting computers anywhere
brew "nebula"
# Incremental parsing library
brew "tree-sitter"
# Very basic terminfo library
brew "unibilium"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# High dynamic-range image file format
brew "openexr"
# Development kit for the Java programming language
brew "openjdk@21"
# SDK for building Kubernetes applications
brew "operator-sdk"
# OCI Registry As Storage
brew "oras"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Fast, disk space efficient package manager
brew "pnpm"
# Tool for managing OCI containers and pods
brew "podman"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Object-relational database system
brew "postgresql@14"
# Python version management
brew "pyenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Easily detect and prevent bugs and anti-patterns in your codebase
brew "semgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Work with remote images registries
brew "skopeo"
# S/MIME signing utility for use with Git
brew "smimesign"
# Launcher to analyze a project with SonarQube
brew "sonar-scanner"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# CLI for generating a Software Bill of Materials from container images
brew "syft"
# Official tldr client written in Rust
brew "tlrc"
# Instant terminal sharing
brew "tmate"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Parser generator tool
brew "tree-sitter-cli"
# Vulnerability scanner for container images, file systems, and Git repos
brew "trivy"
# Validating, recursive, caching DNS resolver
brew "unbound"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Virtual Audio Driver
cask "blackhole-16ch"
# Web security testing toolkit
cask "burp-suite"
# Universal database tool and SQL client
cask "dbeaver-community"
# App to build and share containerised applications and microservices
cask "docker-desktop"
# Online diagram software
cask "drawio"
# Web browser
cask "firefox"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Open-source keystroke visualiser
cask "keycastr"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Collaboration platform for API development
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Open-source code editor
cask "visual-studio-code"
vscode "13xforever.language-x86-64-assembly"
vscode "alexcvzz.vscode-sqlite"
vscode "arcticicestudio.nord-visual-studio-code"
vscode "asvetliakov.vscode-neovim"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "continue.continue"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dendron.dendron"
vscode "dendron.dendron-markdown-shortcuts"
vscode "dendron.dendron-paste-image"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "ewrenn.vscode-ytt"
vscode "github.codespaces"
vscode "github.github-vscode-theme"
vscode "github.vscode-codeql"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "james-yu.latex-workshop"
vscode "juanblanco.solidity"
vscode "k--kato.intellij-idea-keybindings"
vscode "ludwigm.vscode-network-logger"
vscode "luveti.kconfig"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mathiasfrohlich.kotlin"
vscode "mechatroner.rainbow-csv"
vscode "meezilla.json"
vscode "moshfeu.compare-folders"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-mssql.mssql"
vscode "ms-mssql.sql-bindings-vscode"
vscode "ms-mssql.sql-database-projects-vscode"
vscode "ms-playwright.playwright"
vscode "ms-python.autopep8"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.datawrangler"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "plorefice.devicetree"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "rust-lang.rust-analyzer"
vscode "saoudrizwan.claude-dev"
vscode "statiolake.vscode-rustfmt"
vscode "tauri-apps.tauri-vscode"
vscode "timonwong.shellcheck"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "vadimcn.vscode-lldb"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "webfreak.debug"
vscode "zainchen.json"
cargo "cargo-generate"
cargo "cargo-watch"
cargo "clap"
cargo "create-tauri-app"
cargo "gitlab-tree"
cargo "loco-cli"
cargo "mdbook"
cargo "rustlings"
cargo "samply"
cargo "sea-orm-cli"
cargo "tauri-cli"
uv "ruff"
npm "@earendil-works/pi-coding-agent"
npm "corepack"
